version: "3.8"

services:
  cronicle-master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronicle-master
    environment:
      - CRONICLE_role=master
      - TZ=Europe/Zurich
    volumes:
      - cronicle_data:/opt/cronicle/data
      - cronicle_logs:/opt/cronicle/logs
      - /var/scripts:/opt/scripts
      - /var/cronicle/plugins:/opt/cronicle/plugins
      - meta_data:/opt/meta:rw
    ports:
      - "3012:3012"   # Web GUI
    networks:
      - cronicle_net
    restart: unless-stopped

  cronicle-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cronicle-worker
    environment:
      - CRONICLE_role=worker
      - CRONICLE_master_host=cronicle-master
      - TZ=Europe/Zurich
    volumes:
      - cronicle_data:/opt/cronicle/data
      - cronicle_logs:/opt/cronicle/logs
      - /var/scripts:/opt/scripts
      - /var/cronicle/plugins:/opt/cronicle/plugins
      - meta_data:/opt/meta:rw
    networks:
      - cronicle_net
    depends_on:
      - cronicle-master
    restart: unless-stopped

volumes:
  cronicle_data:
  cronicle_logs:
  meta_data:
    external:
      name: meta_data

networks:
  cronicle_net:
